In [6]:
from pathlib import Path
import os, sys

repo_root = Path.cwd()
while repo_root.name != "DenseFlow_Tool-main" and repo_root.parent != repo_root:
    repo_root = repo_root.parent
os.chdir(repo_root)
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

In [7]:
import importlib
import numpy as np
import time
import Code.myHoloscope as myHoloscope
import Code.myMaxflow as myMaxflow
import Code.Check as check
import Code.info as info
import Code.holodatatran as holo
import Code.Cubedatatran as cube
import Code.Datatran_1 as dt
import Code.compare_method as cm
importlib.reload(myHoloscope)
importlib.reload(myMaxflow)
from Code.myHoloscope import *
from Code.myMaxflow import *
from Code.Check import *
from Code.info import *
if not hasattr(np, 'int'):
    np.int = int
if not hasattr(time, 'clock'):
    time.clock = time.perf_counter
caseing = ['PlusTokenPonzi']
caseandk = {'PlusTokenPonzi':10 }

In [8]:
from pathlib import Path
import ast
import pandas as pd

base = Path('./inputData/AML')
data_base = base / 'data'
cases_now = ['AlphaHomora', 'CryptopiaHacker', 'PlusTokenPonzi']

def ensure_normal_tx(case):
    case_dir = base / case
    normal_tx = case_dir / 'all-normal-tx.csv'
    if normal_tx.exists():
        return normal_tx

    all_tx = case_dir / 'all-tx.csv'
    cube_xy = case_dir / 'all-normal-tx-cube_xy.csv'
    addr_csv = case_dir / 'all-address.csv'

    if all_tx.exists():
        print(f'[{case}] building all-normal-tx.csv from all-tx.csv')
        df = pd.read_csv(all_tx)
        if 'isError' not in df.columns:
            df['isError'] = 0
        df.to_csv(normal_tx, index=False)
        return normal_tx

    if cube_xy.exists() and addr_csv.exists():
        print(f'[{case}] building all-normal-tx.csv from cube_xy + all-address')
        cube = pd.read_csv(cube_xy, header=None, names=['from_id', 'to_id', 'timeStamp', 'value'])
        addr = pd.read_csv(addr_csv)
        addresses = addr['address'].astype(str).tolist()
        max_idx = int(max(cube['from_id'].max(), cube['to_id'].max()))
        if max_idx >= len(addresses):
            raise ValueError(f'[{case}] address list too short for cube ids: {max_idx} >= {len(addresses)}')
        cube['from'] = cube['from_id'].astype(int).map(lambda i: addresses[i])
        cube['to'] = cube['to_id'].astype(int).map(lambda i: addresses[i])
        out = pd.DataFrame({
            'hash': [f'{case}_{i}' for i in range(len(cube))],
            'from': cube['from'],
            'to': cube['to'],
            'value': pd.to_numeric(cube['value'], errors='coerce').fillna(0.0),
            'timeStamp': pd.to_numeric(cube['timeStamp'], errors='coerce').fillna(0).astype(int),
            'blockNumber': 0,
            'tokenSymbol': '',
            'contractAddress': '',
            'isError': 0,
            'gasPrice': 0,
            'gasUsed': 0,
        })
        out.to_csv(normal_tx, index=False)
        return normal_tx

    raise FileNotFoundError(f'[{case}] missing source files to build all-normal-tx.csv')

def ensure_addr_maps(case, normal_tx):
    case_data_dir = data_base / case
    case_data_dir.mkdir(parents=True, exist_ok=True)
    from_file = case_data_dir / 'all-normal-tx_from.txt'
    to_file = case_data_dir / 'all-normal-tx_to.txt'

    if from_file.exists() and to_file.exists():
        from_list = ast.literal_eval(from_file.read_text(encoding='utf-8'))
        to_list = ast.literal_eval(to_file.read_text(encoding='utf-8'))
        from_map = {addr: idx for idx, addr in from_list}
        to_map = {addr: idx for idx, addr in to_list}
        return from_map, to_map

    df = pd.read_csv(normal_tx)
    df['value'] = pd.to_numeric(df['value'], errors='coerce').fillna(0.0)
    df = df[df['value'] != 0.0].copy()
    df['from'] = df['from'].astype(str)
    df['to'] = df['to'].astype(str)

    from_addrs = pd.unique(df['from'])
    to_addrs = pd.unique(df['to'])
    from_list = list(enumerate(from_addrs.tolist()))
    to_list = list(enumerate(to_addrs.tolist()))
    from_file.write_text(str(from_list), encoding='utf-8')
    to_file.write_text(str(to_list), encoding='utf-8')
    from_map = {addr: idx for idx, addr in from_list}
    to_map = {addr: idx for idx, addr in to_list}
    return from_map, to_map

def ensure_holo_tx(case, normal_tx, from_map, to_map):
    case_dir = base / case
    holo_file = case_dir / 'all-normal-tx_holo.csv'
    if holo_file.exists():
        return

    print(f'[{case}] building all-normal-tx_holo.csv from all-normal-tx.csv')
    df = pd.read_csv(normal_tx)
    df['value'] = pd.to_numeric(df['value'], errors='coerce').fillna(0.0)
    df = df[df['value'] != 0.0].copy()
    df['timeStamp'] = pd.to_numeric(df['timeStamp'], errors='coerce').fillna(0).astype(int)
    df['from'] = df['from'].astype(str)
    df['to'] = df['to'].astype(str)
    df = df[df['from'].isin(from_map) & df['to'].isin(to_map)]

    dates = pd.to_datetime(df['timeStamp'], unit='s', utc=True, errors='coerce').dt.strftime('%Y-%m-%d')
    holo_df = pd.DataFrame({
        0: df['from'].map(from_map).astype('int64'),
        1: df['to'].map(to_map).astype('int64'),
        2: dates,
        3: df['value'].astype(float),
        4: 1,
    }).dropna(subset=[2])
    holo_df.to_csv(holo_file)

for casename in cases_now:
    print(f'Preparing {casename} ...')
    normal_tx = ensure_normal_tx(casename)
    from_a2n, to_a2n = ensure_addr_maps(casename, normal_tx)
    ensure_holo_tx(casename, normal_tx, from_a2n, to_a2n)
    print(f'[{casename}] preparation complete')

Preparing AlphaHomora ...
[AlphaHomora] preparation complete
Preparing CryptopiaHacker ...
[CryptopiaHacker] preparation complete
Preparing PlusTokenPonzi ...
[PlusTokenPonzi] preparation complete

In [9]:
CASES

['AlphaHomora',
 'AscendEXHacker',
 'FakeMetadiumPresale',
 'KucoinHacker',
 'PlusTokenPonzi',
 'UpbitHack']

In [10]:
cases_now = ['AlphaHomora', 
             'CryptopiaHacker', 
             'PlusTokenPonzi'
             ]
for casename in cases_now:
    print('Now processing case',casename,'data preprocessing...\n')
    print('Reading data')
    address = pd.read_csv(f'./inputData/AML/'+casename+'/all-normal-address.csv')
    heist = address.loc[address['label']=='heist']
    heist_address = heist['address'].tolist()
    from_a2n,to_a2n =  holo.addr_to_num(casename)
    from_n2a,to_n2a = holo.num_to_addr(casename)
    filePath =  f'./inputData/AML/'+casename+'/all-normal-tx_holo.csv'
    print('Processing data')
    tensor_data = st.loadTensor(path = filePath, header=None)
    # Format
    tensor_data.data = tensor_data.data.drop(columns=[0])
    tensor_data.data = tensor_data.data.drop([0])
    tensor_data.data.columns=[0,1,2,3,4]
    tensor_data.data[2] = tensor_data.data[2].astype(str).str.replace('/','-')
    tensor_data.data[[0,1,3,4]] = tensor_data.data[[0,1,3,4]].apply(pd.to_numeric, errors='coerce')
    tensor_data.data[2] = pd.to_datetime(tensor_data.data[2], errors='coerce')
    tensor_data.data = tensor_data.data.dropna(subset=[0,1,2,3,4])
    tensor_data.data[3] = pd.cut(tensor_data.data[3], bins=5, labels=[1,2,3,4,5], include_lowest=True).astype('int64')
    tensor_data.data[2] = pd.factorize(tensor_data.data[2])[0]
    tensor_data.data[[0,1,2,3,4]] = tensor_data.data[[0,1,2,3,4]].astype('int64')
    stensor = tensor_data.toSTensor(hasvalue=True)
    graph = st.Graph(stensor, bipartite=True, weighted=True, modet=2)
    hs = st.HoloScope(graph)
    print(casename,'Data construction completed')
    for k in [10, 30]:
        print('Now k=',k,'calculating level=3 results')
        try:
            res3 = hs.run(level=3, k=k)
            add_h3 = outputheist(res3, from_n2a, to_n2a)
            a3 = pd.DataFrame(add_h3, columns=['heist3'])
            out_xlsx = f'./inputData/AML/{casename}/myheist_k_{k}.xlsx'
            with pd.ExcelWriter(out_xlsx) as writer:
                pd.DataFrame(columns=['heist0']).to_excel(writer, 'Sheet0')
                pd.DataFrame(columns=['heist1']).to_excel(writer, 'Sheet1')
                pd.DataFrame(columns=['heist2']).to_excel(writer, 'Sheet2')
                a3.to_excel(writer, 'Sheet3')
            print('Completed',casename,' k=',k,' level=3 result calculation and storage')
        except Exception as e:
            print('Failed',casename,' k=',k,' level=3, error=',e)

Now processing case AlphaHomora data preprocessing...

Reading data
Processing data
AlphaHomora Data construction completed
Now k= 10 calculating level=3 results
initial...
Considering +[topology] +[timestamps] +[sudden drop]+[rating i.e. # of stars]
matrix size: 29696 x 7690	#edges: 83610.0
finished computing weight matrix
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
::::matricize time cost:  0.28504529999997885
matricize 29696x47766 and svd dense... ...
::::Finish Init @  0.3808687000000077
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 12.571826258420984
=== === improved opt size: 1
=== === improved opt value: 12.571826258420984
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 29.31361490464351
=== === improved opt size: 1
=== === improved opt value: 29.31361490464351
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 36.43805068828146
=== === improved opt size: 1
=== === improved opt value: 36.43805068828146
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 1.17549468386771
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
...........................................................................................
*** *** shaving opt size: 273
*** *** shaving opt value: 0.09966914412273016
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
........................................................................................
*** *** shaving opt size: 526
*** *** shaving opt value: 0.08466396329538235
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
....................................................
*** *** shaving opt size: 52
*** *** shaving opt value: 0.17399370864068914
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
...................................................................................
*** *** shaving opt size: 331
*** *** shaving opt value: 0.07057418798128096
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
........
*** *** shaving opt size: 8
*** *** shaving opt value: 0.6989062142926995
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................................................................................
*** *** shaving opt size: 878
*** *** shaving opt value: 0.03482149109756026
::::Finish Algorithm @  4.0209337000000005
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29696x47766 and svd dense... ...
::::Finish Init @  0.08538459999999759
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 12.571826258420984
=== === improved opt size: 1
=== === improved opt value: 12.571826258420984
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 29.31361490464351
=== === improved opt size: 1
=== === improved opt value: 29.31361490464351
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 1.17549468386771
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
...........................................................................................
*** *** shaving opt size: 273
*** *** shaving opt value: 0.09966914412273016
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
........................................................................................
*** *** shaving opt size: 526
*** *** shaving opt value: 0.08466396329538235
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
....................................................
*** *** shaving opt size: 52
*** *** shaving opt value: 0.17399370864068914
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
...................................................................................
*** *** shaving opt size: 331
*** *** shaving opt value: 0.07057418798128096
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
........
*** *** shaving opt size: 8
*** *** shaving opt value: 0.6989062142926995
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................................................................................
*** *** shaving opt size: 878
*** *** shaving opt value: 0.03482149109756026
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.02154293328376604
::::Finish Algorithm @  4.130332400000015
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29696x47766 and svd dense... ...
::::Finish Init @  0.08825960000001487
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 12.571826258420984
=== === improved opt size: 1
=== === improved opt value: 12.571826258420984
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 1.17549468386771
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
...........................................................................................
*** *** shaving opt size: 273
*** *** shaving opt value: 0.09966914412273016
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
........................................................................................
*** *** shaving opt size: 526
*** *** shaving opt value: 0.08466396329538235
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
....................................................
*** *** shaving opt size: 52
*** *** shaving opt value: 0.17399370864068914
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
...................................................................................
*** *** shaving opt size: 331
*** *** shaving opt value: 0.07057418798128096
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
........
*** *** shaving opt size: 8
*** *** shaving opt value: 0.6989062142926995
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................................................................................
*** *** shaving opt size: 878
*** *** shaving opt value: 0.03482149109756026
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.02154293328376604
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
............................................................................
*** *** shaving opt size: 303
*** *** shaving opt value: 0.04586370054414582
::::Finish Algorithm @  4.425678500000004
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29696x47766 and svd dense... ...
::::Finish Init @  0.08804860000000758
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 1.17549468386771
=== === improved opt size: 1
=== === improved opt value: 1.17549468386771
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
...........................................................................................
*** *** shaving opt size: 273
*** *** shaving opt value: 0.09966914412273016
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
........................................................................................
*** *** shaving opt size: 526
*** *** shaving opt value: 0.08466396329538235
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
....................................................
*** *** shaving opt size: 52
*** *** shaving opt value: 0.17399370864068914
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
...................................................................................
*** *** shaving opt size: 331
*** *** shaving opt value: 0.07057418798128096
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
........
*** *** shaving opt size: 8
*** *** shaving opt value: 0.6989062142926995
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................................................................................
*** *** shaving opt size: 878
*** *** shaving opt value: 0.03482149109756026
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.02154293328376604
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
............................................................................
*** *** shaving opt size: 303
*** *** shaving opt value: 0.04586370054414582
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.03570390750631985
::::Finish Algorithm @  5.060420700000009
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29696x47766 and svd dense... ...
::::Finish Init @  0.10526110000000699
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
...........................................................................................
*** *** shaving opt size: 273
*** *** shaving opt value: 0.09966914412273016
=== === improved opt size: 273
=== === improved opt value: 0.09966914412273016
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
........................................................................................
*** *** shaving opt size: 526
*** *** shaving opt value: 0.08466396329538235
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
....................................................
*** *** shaving opt size: 52
*** *** shaving opt value: 0.17399370864068914
=== === improved opt size: 52
=== === improved opt value: 0.17399370864068914
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
...................................................................................
*** *** shaving opt size: 331
*** *** shaving opt value: 0.07057418798128096
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
........
*** *** shaving opt size: 8
*** *** shaving opt value: 0.6989062142926995
=== === improved opt size: 8
=== === improved opt value: 0.6989062142926995
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................................................................................
*** *** shaving opt size: 878
*** *** shaving opt value: 0.03482149109756026
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.02154293328376604
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
............................................................................
*** *** shaving opt size: 303
*** *** shaving opt value: 0.04586370054414582
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.03570390750631985
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
............................................................
*** *** shaving opt size: 119
*** *** shaving opt value: 0.06735076102339478
::::Finish Algorithm @  5.346082899999999
removing 8 rows from graph
removing 8 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29696x47766 and svd dense... ...
::::Finish Init @  0.10818340000000148
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
...........................................................................................
*** *** shaving opt size: 273
*** *** shaving opt value: 0.09966914412273016
=== === improved opt size: 273
=== === improved opt value: 0.09966914412273016
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
........................................................................................
*** *** shaving opt size: 526
*** *** shaving opt value: 0.08466396329538235
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
....................................................
*** *** shaving opt size: 52
*** *** shaving opt value: 0.17399370864068914
=== === improved opt size: 52
=== === improved opt value: 0.17399370864068914
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
...................................................................................
*** *** shaving opt size: 331
*** *** shaving opt value: 0.07057418798128096
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................................................................................
*** *** shaving opt size: 878
*** *** shaving opt value: 0.03482149109756026
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.02154293328376604
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
............................................................................
*** *** shaving opt size: 303
*** *** shaving opt value: 0.04586370054414582
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.03570390750631985
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
............................................................
*** *** shaving opt size: 119
*** *** shaving opt value: 0.06735076102339478
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.561683670476966
=== === improved opt size: 1
=== === improved opt value: 4.561683670476966
::::Finish Algorithm @  5.443841500000019
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29696x47766 and svd dense... ...
::::Finish Init @  0.09852440000000229
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
...........................................................................................
*** *** shaving opt size: 273
*** *** shaving opt value: 0.09966914412273016
=== === improved opt size: 273
=== === improved opt value: 0.09966914412273016
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
........................................................................................
*** *** shaving opt size: 526
*** *** shaving opt value: 0.08466396329538235
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
....................................................
*** *** shaving opt size: 52
*** *** shaving opt value: 0.17399370864068914
=== === improved opt size: 52
=== === improved opt value: 0.17399370864068914
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
...................................................................................
*** *** shaving opt size: 331
*** *** shaving opt value: 0.07057418798128096
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................................................................................
*** *** shaving opt size: 878
*** *** shaving opt value: 0.03482149109756026
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.02154293328376604
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
............................................................................
*** *** shaving opt size: 303
*** *** shaving opt value: 0.04586370054414582
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.03570390750631985
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
............................................................
*** *** shaving opt size: 119
*** *** shaving opt value: 0.06735076102339478
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.....................................................................................
*** *** shaving opt size: 1
*** *** shaving opt value: 0.000320568247416849
::::Finish Algorithm @  5.45944369999998
removing 52 rows from graph
removing 52 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29696x47766 and svd dense... ...
::::Finish Init @  0.09193999999999392
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
...........................................................................................
*** *** shaving opt size: 272
*** *** shaving opt value: 0.0984746838832869
=== === improved opt size: 272
=== === improved opt value: 0.0984746838832869
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
........................................................................................
*** *** shaving opt size: 526
*** *** shaving opt value: 0.08466396329538235
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................................................................
*** *** shaving opt size: 327
*** *** shaving opt value: 0.07134127364649252
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree

c:\Users\sussi\OneDrive\Documents\Denseflow\DenseFlow_Tool\.venv_py38\lib\site-packages\scipy\stats\_continuous_distns.py:6932: RuntimeWarning: divide by zero encountered in scalar divide
  return ndata / np.sum(np.log((data - location) / scale))
c:\Users\sussi\OneDrive\Documents\Denseflow\DenseFlow_Tool\.venv_py38\lib\site-packages\scipy\stats\_continuous_distns.py:6955: RuntimeWarning: invalid value encountered in scalar subtract
  return dL_dLocation(shape, location) - dL_dScale(shape, scale)

Completed AlphaHomora  k= 10  level=3 result calculation and storage
Now k= 30 calculating level=3 results
initial...
Considering +[topology] +[timestamps] +[sudden drop]+[rating i.e. # of stars]
matrix size: 29696 x 7690	#edges: 83610.0
finished computing weight matrix
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
::::matricize time cost:  0.3927888999999709
matricize 29696x47766 and svd dense... ...
::::Finish Init @  0.4852453999999966
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 12.571826258420984
=== === improved opt size: 1
=== === improved opt value: 12.571826258420984
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 29.31361490464351
=== === improved opt size: 1
=== === improved opt value: 29.31361490464351
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 36.43805068828146
=== === improved opt size: 1
=== === improved opt value: 36.43805068828146
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 1.17549468386771
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
...........................................................................................
*** *** shaving opt size: 273
*** *** shaving opt value: 0.09966914412273016
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
........................................................................................
*** *** shaving opt size: 526
*** *** shaving opt value: 0.08466396329538235
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
....................................................
*** *** shaving opt size: 52
*** *** shaving opt value: 0.17399370864068914
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
...................................................................................
*** *** shaving opt size: 331
*** *** shaving opt value: 0.07057418798128096
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
........
*** *** shaving opt size: 8
*** *** shaving opt value: 0.6989062142926995
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................................................................................
*** *** shaving opt size: 878
*** *** shaving opt value: 0.03482149109756026
::::Finish Algorithm @  3.932730499999991
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29696x47766 and svd dense... ...
::::Finish Init @  0.10847289999998111
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 12.571826258420984
=== === improved opt size: 1
=== === improved opt value: 12.571826258420984
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 29.31361490464351
=== === improved opt size: 1
=== === improved opt value: 29.31361490464351
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 1.17549468386771
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
...........................................................................................
*** *** shaving opt size: 273
*** *** shaving opt value: 0.09966914412273016
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
........................................................................................
*** *** shaving opt size: 526
*** *** shaving opt value: 0.08466396329538235
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
....................................................
*** *** shaving opt size: 52
*** *** shaving opt value: 0.17399370864068914
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
...................................................................................
*** *** shaving opt size: 331
*** *** shaving opt value: 0.07057418798128096
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
........
*** *** shaving opt size: 8
*** *** shaving opt value: 0.6989062142926995
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................................................................................
*** *** shaving opt size: 878
*** *** shaving opt value: 0.03482149109756026
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.02154293328376604
::::Finish Algorithm @  3.9510227999999756
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29696x47766 and svd dense... ...
::::Finish Init @  0.08965559999995776
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 12.571826258420984
=== === improved opt size: 1
=== === improved opt value: 12.571826258420984
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 1.17549468386771
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
...........................................................................................
*** *** shaving opt size: 273
*** *** shaving opt value: 0.09966914412273016
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
........................................................................................
*** *** shaving opt size: 526
*** *** shaving opt value: 0.08466396329538235
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
....................................................
*** *** shaving opt size: 52
*** *** shaving opt value: 0.17399370864068914
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
...................................................................................
*** *** shaving opt size: 331
*** *** shaving opt value: 0.07057418798128096
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
........
*** *** shaving opt size: 8
*** *** shaving opt value: 0.6989062142926995
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................................................................................
*** *** shaving opt size: 878
*** *** shaving opt value: 0.03482149109756026
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.02154293328376604
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
............................................................................
*** *** shaving opt size: 303
*** *** shaving opt value: 0.04586370054414582
::::Finish Algorithm @  4.377267599999982
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29696x47766 and svd dense... ...
::::Finish Init @  0.09646530000003395
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 1.17549468386771
=== === improved opt size: 1
=== === improved opt value: 1.17549468386771
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
...........................................................................................
*** *** shaving opt size: 273
*** *** shaving opt value: 0.09966914412273016
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
........................................................................................
*** *** shaving opt size: 526
*** *** shaving opt value: 0.08466396329538235
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
....................................................
*** *** shaving opt size: 52
*** *** shaving opt value: 0.17399370864068914
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
...................................................................................
*** *** shaving opt size: 331
*** *** shaving opt value: 0.07057418798128096
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
........
*** *** shaving opt size: 8
*** *** shaving opt value: 0.6989062142926995
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................................................................................
*** *** shaving opt size: 878
*** *** shaving opt value: 0.03482149109756026
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.02154293328376604
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
............................................................................
*** *** shaving opt size: 303
*** *** shaving opt value: 0.04586370054414582
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.03570390750631985
::::Finish Algorithm @  5.13947330000002
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29696x47766 and svd dense... ...
::::Finish Init @  0.11692499999998063
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
...........................................................................................
*** *** shaving opt size: 273
*** *** shaving opt value: 0.09966914412273016
=== === improved opt size: 273
=== === improved opt value: 0.09966914412273016
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
........................................................................................
*** *** shaving opt size: 526
*** *** shaving opt value: 0.08466396329538235
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
....................................................
*** *** shaving opt size: 52
*** *** shaving opt value: 0.17399370864068914
=== === improved opt size: 52
=== === improved opt value: 0.17399370864068914
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
...................................................................................
*** *** shaving opt size: 331
*** *** shaving opt value: 0.07057418798128096
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
........
*** *** shaving opt size: 8
*** *** shaving opt value: 0.6989062142926995
=== === improved opt size: 8
=== === improved opt value: 0.6989062142926995
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................................................................................
*** *** shaving opt size: 878
*** *** shaving opt value: 0.03482149109756026
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.02154293328376604
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
............................................................................
*** *** shaving opt size: 303
*** *** shaving opt value: 0.04586370054414582
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.03570390750631985
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
............................................................
*** *** shaving opt size: 119
*** *** shaving opt value: 0.06735076102339478
::::Finish Algorithm @  5.241327399999989
removing 8 rows from graph
removing 8 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29696x47766 and svd dense... ...
::::Finish Init @  0.09742469999997638
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
...........................................................................................
*** *** shaving opt size: 273
*** *** shaving opt value: 0.09966914412273016
=== === improved opt size: 273
=== === improved opt value: 0.09966914412273016
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
........................................................................................
*** *** shaving opt size: 526
*** *** shaving opt value: 0.08466396329538235
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
....................................................
*** *** shaving opt size: 52
*** *** shaving opt value: 0.17399370864068914
=== === improved opt size: 52
=== === improved opt value: 0.17399370864068914
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
...................................................................................
*** *** shaving opt size: 331
*** *** shaving opt value: 0.07057418798128096
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................................................................................
*** *** shaving opt size: 878
*** *** shaving opt value: 0.03482149109756026
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.02154293328376604
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
............................................................................
*** *** shaving opt size: 303
*** *** shaving opt value: 0.04586370054414582
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.03570390750631985
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
............................................................
*** *** shaving opt size: 119
*** *** shaving opt value: 0.06735076102339478
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.561683670476966
=== === improved opt size: 1
=== === improved opt value: 4.561683670476966
::::Finish Algorithm @  5.299064499999986
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29696x47766 and svd dense... ...
::::Finish Init @  0.10994870000001811
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
...........................................................................................
*** *** shaving opt size: 273
*** *** shaving opt value: 0.09966914412273016
=== === improved opt size: 273
=== === improved opt value: 0.09966914412273016
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
........................................................................................
*** *** shaving opt size: 526
*** *** shaving opt value: 0.08466396329538235
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
....................................................
*** *** shaving opt size: 52
*** *** shaving opt value: 0.17399370864068914
=== === improved opt size: 52
=== === improved opt value: 0.17399370864068914
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
...................................................................................
*** *** shaving opt size: 331
*** *** shaving opt value: 0.07057418798128096
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................................................................................
*** *** shaving opt size: 878
*** *** shaving opt value: 0.03482149109756026
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.02154293328376604
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
............................................................................
*** *** shaving opt size: 303
*** *** shaving opt value: 0.04586370054414582
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
......................................................................................
*** *** shaving opt size: 343
*** *** shaving opt value: 0.03570390750631985
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
............................................................
*** *** shaving opt size: 119
*** *** shaving opt value: 0.06735076102339478
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.....................................................................................
*** *** shaving opt size: 1
*** *** shaving opt value: 0.000320568247416849
::::Finish Algorithm @  5.4889201999999955
removing 52 rows from graph
removing 52 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29696x47766 and svd dense... ...
::::Finish Init @  0.09863199999995231
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
...........................................................................................
*** *** shaving opt size: 272
*** *** shaving opt value: 0.0984746838832869
=== === improved opt size: 272
=== === improved opt value: 0.0984746838832869
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
........................................................................................
*** *** shaving opt size: 526
*** *** shaving opt value: 0.08466396329538235
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................................................................
*** *** shaving opt size: 327
*** *** shaving opt value: 0.07134127364649252
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................................................................................

c:\Users\sussi\OneDrive\Documents\Denseflow\DenseFlow_Tool\.venv_py38\lib\site-packages\scipy\stats\_continuous_distns.py:6932: RuntimeWarning: divide by zero encountered in scalar divide
  return ndata / np.sum(np.log((data - location) / scale))
c:\Users\sussi\OneDrive\Documents\Denseflow\DenseFlow_Tool\.venv_py38\lib\site-packages\scipy\stats\_continuous_distns.py:6955: RuntimeWarning: invalid value encountered in scalar subtract
  return dL_dLocation(shape, location) - dL_dScale(shape, scale)

Completed AlphaHomora  k= 30  level=3 result calculation and storage
Now processing case CryptopiaHacker data preprocessing...

Reading data
Processing data
CryptopiaHacker Data construction completed
Now k= 10 calculating level=3 results
initial...
Considering +[topology] +[timestamps] +[sudden drop]+[rating i.e. # of stars]
matrix size: 35528 x 82581	#edges: 315169.0
finished computing weight matrix
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
::::matricize time cost:  1.1394881999999598
matricize 35528x170269 and svd dense... ...
::::Finish Init @  1.2665848000000324
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 34.42924114267665
=== === improved opt size: 1
=== === improved opt value: 34.42924114267665
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 78.44736167478264
=== === improved opt size: 1
=== === improved opt value: 78.44736167478264
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 233.4127344286019
=== === improved opt size: 1
=== === improved opt value: 233.4127344286019
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 195.9314090054899
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 80.7106492288916
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 56.15249166728581
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 93.43551771760183
::::Finish Algorithm @  4.069076800000005
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 35528x170269 and svd dense... ...
::::Finish Init @  0.11994740000000093
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 34.42924114267665
=== === improved opt size: 1
=== === improved opt value: 34.42924114267665
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 78.44736167478264
=== === improved opt size: 1
=== === improved opt value: 78.44736167478264
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 195.9314090054899
=== === improved opt size: 1
=== === improved opt value: 195.9314090054899
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 80.7106492288916
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 56.15249166728581
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 93.43551771760183
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 30.77755169763601
::::Finish Algorithm @  2.94056089999998
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 35528x170269 and svd dense... ...
::::Finish Init @  0.11822879999999714
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 34.42924114267665
=== === improved opt size: 1
=== === improved opt value: 34.42924114267665
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 78.44736167478264
=== === improved opt size: 1
=== === improved opt value: 78.44736167478264
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 80.7106492288916
=== === improved opt size: 1
=== === improved opt value: 80.7106492288916
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 56.15249166728581
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 93.43551771760183
=== === improved opt size: 1
=== === improved opt value: 93.43551771760183
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 30.77755169763601
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 11.066790049367357
::::Finish Algorithm @  2.8435617000000093
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 35528x170269 and svd dense... ...
::::Finish Init @  0.1136925000000133
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 34.42924114267665
=== === improved opt size: 1
=== === improved opt value: 34.42924114267665
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 78.44736167478264
=== === improved opt size: 1
=== === improved opt value: 78.44736167478264
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 80.7106492288916
=== === improved opt size: 1
=== === improved opt value: 80.7106492288916
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 56.15249166728581
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 30.77755169763601
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 11.066790049367357
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 46.2644620997241
::::Finish Algorithm @  2.8077560000000403
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 35528x170269 and svd dense... ...
::::Finish Init @  0.11855369999994991
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 34.42924114267665
=== === improved opt size: 1
=== === improved opt value: 34.42924114267665
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 78.44736167478264
=== === improved opt size: 1
=== === improved opt value: 78.44736167478264
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 56.15249166728581
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 30.77755169763601
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 11.066790049367357
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 46.2644620997241
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 7.706846920044118
::::Finish Algorithm @  2.889973399999974
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 35528x170269 and svd dense... ...
::::Finish Init @  0.11798650000002908
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 34.42924114267665
=== === improved opt size: 1
=== === improved opt value: 34.42924114267665
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 56.15249166728581
=== === improved opt size: 1
=== === improved opt value: 56.15249166728581
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 30.77755169763601
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 11.066790049367357
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 46.2644620997241
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 7.706846920044118
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 32.59363878055927
::::Finish Algorithm @  3.0574053000000276
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 35528x170269 and svd dense... ...
::::Finish Init @  0.12906759999998485
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 34.42924114267665
=== === improved opt size: 1
=== === improved opt value: 34.42924114267665
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 30.77755169763601
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 11.066790049367357
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 46.2644620997241
=== === improved opt size: 1
=== === improved opt value: 46.2644620997241
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 7.706846920044118
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 32.59363878055927
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
....
*** *** shaving opt size: 3
*** *** shaving opt value: 5.70642320647011
::::Finish Algorithm @  2.8266024999999786
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 35528x170269 and svd dense... ...
::::Finish Init @  0.12802450000003773
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 34.42924114267665
=== === improved opt size: 1
=== === improved opt value: 34.42924114267665
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 30.77755169763601
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 11.066790049367357
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 7.706846920044118
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 32.59363878055927
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
....
*** *** shaving opt size: 3
*** *** shaving opt value: 5.70642320647011
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 17.15283872136018
::::Finish Algorithm @  2.8610179000000358
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 35528x170269 and svd dense... ...
::::Finish Init @  0.13880369999998265
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
=== === improved opt size: 1
=== === improved opt value: 4.2586357992240425
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 30.77755169763601
=== === improved opt size: 1
=== === improved opt value: 30.77755169763601
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 11.066790049367357
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 7.706846920044118
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 32.59363878055927
=== === improved opt size: 1
=== === improved opt value: 32.59363878055927
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
....
*** *** shaving opt size: 3
*** *** shaving opt value: 5.70642320647011
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 17.15283872136018
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 52.8029527272358
=== === improved opt size: 1
=== === improved opt value: 52.8029527272358
::::Finish Algorithm @  2.878953200000012
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 35528x170269 and svd dense... ...
::::Finish Init @  0.15497070000003532
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
=== === improved opt size: 1
=== === improved opt value: 4.2586357992240425
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 30.77755169763601
=== === improved opt size: 1
=== === improved opt value: 30.77755169763601
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 11.066790049367357
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 7.706846920044118
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree

c:\Users\sussi\OneDrive\Documents\Denseflow\DenseFlow_Tool\.venv_py38\lib\site-packages\scipy\stats\_continuous_distns.py:6932: RuntimeWarning: divide by zero encountered in scalar divide
  return ndata / np.sum(np.log((data - location) / scale))
c:\Users\sussi\OneDrive\Documents\Denseflow\DenseFlow_Tool\.venv_py38\lib\site-packages\scipy\stats\_continuous_distns.py:6955: RuntimeWarning: invalid value encountered in scalar subtract
  return dL_dLocation(shape, location) - dL_dScale(shape, scale)

	Node size: 1 x 1, edge size 1
	Row and nonzero columns 1 x 9, edge size: 9 with camouflage.
Completed CryptopiaHacker  k= 10  level=3 result calculation and storage
Now k= 30 calculating level=3 results
initial...
Considering +[topology] +[timestamps] +[sudden drop]+[rating i.e. # of stars]
matrix size: 35528 x 82581	#edges: 315169.0
finished computing weight matrix
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
::::matricize time cost:  1.1900190000000066
matricize 35528x170269 and svd dense... ...
::::Finish Init @  1.3192387999999937
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 34.42924114267665
=== === improved opt size: 1
=== === improved opt value: 34.42924114267665
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 78.44736167478264
=== === improved opt size: 1
=== === improved opt value: 78.44736167478264
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 233.4127344286019
=== === improved opt size: 1
=== === improved opt value: 233.4127344286019
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 195.9314090054899
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 80.7106492288916
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 56.15249166728581
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 93.43551771760183
::::Finish Algorithm @  4.166427199999987
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 35528x170269 and svd dense... ...
::::Finish Init @  0.1140887000000248
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 34.42924114267665
=== === improved opt size: 1
=== === improved opt value: 34.42924114267665
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 78.44736167478264
=== === improved opt size: 1
=== === improved opt value: 78.44736167478264
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 195.9314090054899
=== === improved opt size: 1
=== === improved opt value: 195.9314090054899
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 80.7106492288916
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 56.15249166728581
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 93.43551771760183
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 30.77755169763601
::::Finish Algorithm @  2.89865020000002
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 35528x170269 and svd dense... ...
::::Finish Init @  0.12326319999999669
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 34.42924114267665
=== === improved opt size: 1
=== === improved opt value: 34.42924114267665
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 78.44736167478264
=== === improved opt size: 1
=== === improved opt value: 78.44736167478264
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 80.7106492288916
=== === improved opt size: 1
=== === improved opt value: 80.7106492288916
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 56.15249166728581
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 93.43551771760183
=== === improved opt size: 1
=== === improved opt value: 93.43551771760183
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 30.77755169763601
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 11.066790049367357
::::Finish Algorithm @  3.0400905000000193
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 35528x170269 and svd dense... ...
::::Finish Init @  0.11584700000003068
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 34.42924114267665
=== === improved opt size: 1
=== === improved opt value: 34.42924114267665
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 78.44736167478264
=== === improved opt size: 1
=== === improved opt value: 78.44736167478264
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 80.7106492288916
=== === improved opt size: 1
=== === improved opt value: 80.7106492288916
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 56.15249166728581
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 30.77755169763601
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 11.066790049367357
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 46.2644620997241
::::Finish Algorithm @  2.991105600000026
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 35528x170269 and svd dense... ...
::::Finish Init @  0.1239039999999818
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 34.42924114267665
=== === improved opt size: 1
=== === improved opt value: 34.42924114267665
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 78.44736167478264
=== === improved opt size: 1
=== === improved opt value: 78.44736167478264
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 56.15249166728581
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 30.77755169763601
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 11.066790049367357
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 46.2644620997241
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 7.706846920044118
::::Finish Algorithm @  2.936958300000015
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 35528x170269 and svd dense... ...
::::Finish Init @  0.11759459999996125
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 34.42924114267665
=== === improved opt size: 1
=== === improved opt value: 34.42924114267665
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 56.15249166728581
=== === improved opt size: 1
=== === improved opt value: 56.15249166728581
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 30.77755169763601
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 11.066790049367357
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 46.2644620997241
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 7.706846920044118
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 32.59363878055927
::::Finish Algorithm @  2.99405680000001
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 35528x170269 and svd dense... ...
::::Finish Init @  0.12844159999997373
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 34.42924114267665
=== === improved opt size: 1
=== === improved opt value: 34.42924114267665
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 30.77755169763601
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 11.066790049367357
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 46.2644620997241
=== === improved opt size: 1
=== === improved opt value: 46.2644620997241
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 7.706846920044118
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 32.59363878055927
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
....
*** *** shaving opt size: 3
*** *** shaving opt value: 5.70642320647011
::::Finish Algorithm @  2.890818999999965
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 35528x170269 and svd dense... ...
::::Finish Init @  0.12441440000003468
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 34.42924114267665
=== === improved opt size: 1
=== === improved opt value: 34.42924114267665
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 30.77755169763601
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 11.066790049367357
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 7.706846920044118
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 32.59363878055927
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
....
*** *** shaving opt size: 3
*** *** shaving opt value: 5.70642320647011
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 17.15283872136018
::::Finish Algorithm @  2.837421300000017
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 35528x170269 and svd dense... ...
::::Finish Init @  0.1349644000000012
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
=== === improved opt size: 1
=== === improved opt value: 4.2586357992240425
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 30.77755169763601
=== === improved opt size: 1
=== === improved opt value: 30.77755169763601
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 11.066790049367357
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 7.706846920044118
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 32.59363878055927
=== === improved opt size: 1
=== === improved opt value: 32.59363878055927
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
....
*** *** shaving opt size: 3
*** *** shaving opt value: 5.70642320647011
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 17.15283872136018
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 52.8029527272358
=== === improved opt size: 1
=== === improved opt value: 52.8029527272358
::::Finish Algorithm @  2.8136015000000043
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 35528x170269 and svd dense... ...
::::Finish Init @  0.1637389999999641
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 4.2586357992240425
=== === improved opt size: 1
=== === improved opt value: 4.2586357992240425
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.951968219597378
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 3.8475581912889147
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 30.77755169763601
=== === improved opt size: 1
=== === improved opt value: 30.77755169763601
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 11.066790049367357
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 7.706846920044118
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1

c:\Users\sussi\OneDrive\Documents\Denseflow\DenseFlow_Tool\.venv_py38\lib\site-packages\scipy\stats\_continuous_distns.py:6932: RuntimeWarning: divide by zero encountered in scalar divide
  return ndata / np.sum(np.log((data - location) / scale))
c:\Users\sussi\OneDrive\Documents\Denseflow\DenseFlow_Tool\.venv_py38\lib\site-packages\scipy\stats\_continuous_distns.py:6955: RuntimeWarning: invalid value encountered in scalar subtract
  return dL_dLocation(shape, location) - dL_dScale(shape, scale)

	Row and nonzero columns 1 x 22, edge size: 22 with camouflage.
block10:
	objective value 35.55910006115707
	Node size: 1 x 1, edge size 1
	Row and nonzero columns 1 x 9, edge size: 9 with camouflage.
block11:
	objective value 32.59363878055927
	Node size: 1 x 1, edge size 1
	Row and nonzero columns 1 x 1, edge size: 1 with camouflage.
block12:
	objective value 30.77755169763601
	Node size: 1 x 1, edge size 1
	Row and nonzero columns 1 x 1, edge size: 1 with camouflage.
block13:
	objective value 17.15283872136018
	Node size: 1 x 1, edge size 1
	Row and nonzero columns 1 x 6, edge size: 6 with camouflage.
block14:
	objective value 12.750121226177518
	Node size: 1 x 1, edge size 1
	Row and nonzero columns 1 x 21, edge size: 21 with camouflage.
block15:
	objective value 11.066790049367357
	Node size: 1 x 3, edge size 3
	Row and nonzero columns 1 x 349, edge size: 349 with camouflage.
block16:
	objective value 31.170376444368316
	Node size: 1 x 1, edge size 1
	Row and nonzero columns 1 x 91, edge size: 91 with camouflage.
block17:
	objective value 80.65067862468204
	Node size: 1 x 1, edge size 1
	Row and nonzero columns 1 x 1, edge size: 1 with camouflage.
block18:
	objective value 7.706846920044118
	Node size: 1 x 3, edge size 3
	Row and nonzero columns 1 x 769, edge size: 769 with camouflage.
block19:
	objective value 31.619693072585072
	Node size: 1 x 1, edge size 1
	Row and nonzero columns 1 x 2, edge size: 2 with camouflage.
block20:
	objective value 7.0983186844534645
	Node size: 6 x 1, edge size 6
	Row and nonzero columns 6 x 1, edge size: 6 with camouflage.
block21:
	objective value 14.193380991255617
	Node size: 1 x 1, edge size 1
	Row and nonzero columns 1 x 1, edge size: 1 with camouflage.
block22:
	objective value 5.70642320647011
	Node size: 3 x 9, edge size 12
	Row and nonzero columns 3 x 991, edge size: 1002 with camouflage.
block23:
	objective value 36.60709691484969
	Node size: 1 x 1, edge size 1
	Row and nonzero columns 1 x 3, edge size: 3 with camouflage.
block24:
	objective value 21.042264004564764
	Node size: 1 x 1, edge size 1
	Row and nonzero columns 1 x 1, edge size: 1 with camouflage.
block25:
	objective value 5.475408938559925
	Node size: 1 x 1, edge size 1
	Row and nonzero columns 1 x 27, edge size: 27 with camouflage.
block26:
	objective value 6.284635506146168
	Node size: 1 x 1, edge size 1
	Row and nonzero columns 1 x 1, edge size: 1 with camouflage.
block27:
	objective value 5.205490124226544
	Node size: 1 x 4, edge size 4
	Row and nonzero columns 1 x 351, edge size: 351 with camouflage.
block28:
	objective value 4.652518571071152
	Node size: 1 x 1, edge size 1
	Row and nonzero columns 1 x 33, edge size: 33 with camouflage.
block29:
	objective value 4.2586357992240425
	Node size: 1 x 6, edge size 6
	Row and nonzero columns 1 x 1134, edge size: 1134 with camouflage.
block30:
	objective value 3.951968219597378
	Node size: 1 x 12, edge size 12
	Row and nonzero columns 1 x 987, edge size: 987 with camouflage.
Completed CryptopiaHacker  k= 30  level=3 result calculation and storage
Now processing case PlusTokenPonzi data preprocessing...

Reading data
Processing data
PlusTokenPonzi Data construction completed
Now k= 10 calculating level=3 results
initial...
Considering +[topology] +[timestamps] +[sudden drop]+[rating i.e. # of stars]
matrix size: 29529 x 34337	#edges: 52893.0
finished computing weight matrix
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
::::matricize time cost:  0.3226092999999537
matricize 29529x39517 and svd dense... ...
::::Finish Init @  0.40883500000006734
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
....
*** *** shaving opt size: 4
*** *** shaving opt value: 4.022239608827926
=== === improved opt size: 4
=== === improved opt value: 4.022239608827926
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 1.3669003723665814
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
..
*** *** shaving opt size: 2
*** *** shaving opt value: 2.708935584020059
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
...
*** *** shaving opt size: 3
*** *** shaving opt value: 0.9141095445163271
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 1.6243971945889435
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
..
*** *** shaving opt size: 2
*** *** shaving opt value: 0.0035806674674313216
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
......................................
*** *** shaving opt size: 38
*** *** shaving opt value: 0.2143533858380568
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.....................
*** *** shaving opt size: 21
*** *** shaving opt value: 0.09884530955140859
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................
*** *** shaving opt size: 34
*** *** shaving opt value: 0.1152696953714159
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 7
*** *** shaving opt value: 0.0011945706309687903
::::Finish Algorithm @  1.710374100000081
removing 4 rows from graph
removing 4 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29529x39517 and svd dense... ...
::::Finish Init @  0.09465099999999893
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
..
*** *** shaving opt size: 2
*** *** shaving opt value: 2.708935584020059
=== === improved opt size: 2
=== === improved opt value: 2.708935584020059
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 1.6243971945889435
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
......................................
*** *** shaving opt size: 38
*** *** shaving opt value: 0.2143533858380568
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.....................
*** *** shaving opt size: 21
*** *** shaving opt value: 0.09884530955140859
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................
*** *** shaving opt size: 34
*** *** shaving opt value: 0.1152696953714159
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 7
*** *** shaving opt value: 0.0011945706309687903
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
........................
*** *** shaving opt size: 24
*** *** shaving opt value: 0.24359312836819708
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.........................
*** *** shaving opt size: 25
*** *** shaving opt value: 0.03160300114972221
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.00030263586982014163
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.........................
*** *** shaving opt size: 25
*** *** shaving opt value: 0.025839985484651815
::::Finish Algorithm @  1.5444122999999763
removing 2 rows from graph
removing 2 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29529x39517 and svd dense... ...
::::Finish Init @  0.09746700000005148
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
......................................
*** *** shaving opt size: 38
*** *** shaving opt value: 0.2143533858380568
=== === improved opt size: 38
=== === improved opt value: 0.2143533858380568
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.....................
*** *** shaving opt size: 21
*** *** shaving opt value: 0.09884530955140859
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................
*** *** shaving opt size: 34
*** *** shaving opt value: 0.1152696953714159
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 7
*** *** shaving opt value: 0.0011945706309687903
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
........................
*** *** shaving opt size: 24
*** *** shaving opt value: 0.24359312836819708
=== === improved opt size: 24
=== === improved opt value: 0.24359312836819708
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.........................
*** *** shaving opt size: 25
*** *** shaving opt value: 0.03160300114972221
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.00030263586982014163
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.........................
*** *** shaving opt size: 25
*** *** shaving opt value: 0.025839985484651815
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
............
*** *** shaving opt size: 12
*** *** shaving opt value: 0.08782115753412927
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.....................................
*** *** shaving opt size: 36
*** *** shaving opt value: 0.019042535034774422
::::Finish Algorithm @  1.7318516000000272
removing 24 rows from graph
removing 24 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29529x39517 and svd dense... ...
::::Finish Init @  0.11233000000004267
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
......................................
*** *** shaving opt size: 38
*** *** shaving opt value: 0.2143533858380568
=== === improved opt size: 38
=== === improved opt value: 0.2143533858380568
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.....................
*** *** shaving opt size: 21
*** *** shaving opt value: 0.09884530955140859
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................
*** *** shaving opt size: 34
*** *** shaving opt value: 0.1152696953714159
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 7
*** *** shaving opt value: 0.0011945706309687903
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.........................
*** *** shaving opt size: 25
*** *** shaving opt value: 0.03160300114972221
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.00030263586982014163
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.........................
*** *** shaving opt size: 25
*** *** shaving opt value: 0.025839985484651815
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.....................................
*** *** shaving opt size: 36
*** *** shaving opt value: 0.019042535034774422
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
..............................
*** *** shaving opt size: 30
*** *** shaving opt value: 0.010386748076143752
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.0019467122510239251
::::Finish Algorithm @  1.5873698000000331
removing 38 rows from graph
removing 38 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29529x39517 and svd dense... ...
::::Finish Init @  0.09008810000000267
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.....................
*** *** shaving opt size: 21
*** *** shaving opt value: 0.09884530955140859
=== === improved opt size: 21
=== === improved opt value: 0.09884530955140859
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.00030263586982014163
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
..................
*** *** shaving opt size: 18
*** *** shaving opt value: 0.01112787338232485
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.0019467122510239251
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.........................................
*** *** shaving opt size: 41
*** *** shaving opt value: 0.04989758783370213
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.........
*** *** shaving opt size: 4
*** *** shaving opt value: 0.001436606360482448
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 7
*** *** shaving opt value: 0.0014248341826453596
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
...........
*** *** shaving opt size: 11
*** *** shaving opt value: 0.0018221379302836352
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.........
*** *** shaving opt size: 8
*** *** shaving opt value: 0.016523968854082048
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.002680380772836786
::::Finish Algorithm @  1.4881987999999637
removing 21 rows from graph
removing 21 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29529x39517 and svd dense... ...
::::Finish Init @  0.13349219999997786
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.00030263586982014163
=== === improved opt size: 1
=== === improved opt value: 0.00030263586982014163
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.0019467122510239251
=== === improved opt size: 1
=== === improved opt value: 0.0019467122510239251
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.........................................
*** *** shaving opt size: 41
*** *** shaving opt value: 0.04989758783370213
=== === improved opt size: 41
=== === improved opt value: 0.04989758783370213
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 4
*** *** shaving opt value: 0.0014365745860973826
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
...........
*** *** shaving opt size: 11
*** *** shaving opt value: 0.0018221379302836352
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.........
*** *** shaving opt size: 8
*** *** shaving opt value: 0.016523968854082048
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.002680380772836786
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.................
*** *** shaving opt size: 3
*** *** shaving opt value: 0.05565054318679176
=== === improved opt size: 3
=== === improved opt value: 0.05565054318679176
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
...........
*** *** shaving opt size: 10
*** *** shaving opt value: 0.054877745578120904
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
..............
*** *** shaving opt size: 14
*** *** shaving opt value: 0.0019747009257595105
::::Finish Algorithm @  1.4375780000000304
removing 3 rows from graph
removing 3 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29529x39517 and svd dense... ...
::::Finish Init @  0.12310260000003836
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.00030263586982014163
=== === improved opt size: 1
=== === improved opt value: 0.00030263586982014163
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.0019467122510239251
=== === improved opt size: 1
=== === improved opt value: 0.0019467122510239251
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 4
*** *** shaving opt value: 0.0014365745860973826
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.......................................
*** *** shaving opt size: 39
*** *** shaving opt value: 0.04738318394619504
=== === improved opt size: 39
=== === improved opt value: 0.04738318394619504
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
...........
*** *** shaving opt size: 11
*** *** shaving opt value: 0.0018221379302836352
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.........
*** *** shaving opt size: 8
*** *** shaving opt value: 0.016523968854082048
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.002680380772836786
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
................
*** *** shaving opt size: 11
*** *** shaving opt value: 0.020416180555691894
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
...........
*** *** shaving opt size: 11
*** *** shaving opt value: 0.007300061236663409
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
..............
*** *** shaving opt size: 14
*** *** shaving opt value: 0.0019747009257595105
::::Finish Algorithm @  1.5455888000000186
removing 39 rows from graph
removing 39 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29529x39517 and svd dense... ...
::::Finish Init @  0.1463059999999814
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.00030263586982014163
=== === improved opt size: 1
=== === improved opt value: 0.00030263586982014163
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.0019467122510239251
=== === improved opt size: 1
=== === improved opt value: 0.0019467122510239251
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 4
*** *** shaving opt value: 0.0014365745860973826
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
...........
*** *** shaving opt size: 11
*** *** shaving opt value: 0.0018221379302836352
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.........
*** *** shaving opt size: 8
*** *** shaving opt value: 0.016523968854082048
=== === improved opt size: 8
=== === improved opt value: 0.016523968854082048
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.002680380772836786
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 7
*** *** shaving opt value: 0.00039868425474085195

c:\Users\sussi\OneDrive\Documents\Denseflow\DenseFlow_Tool\.venv_py38\lib\site-packages\scipy\stats\_continuous_distns.py:6932: RuntimeWarning: divide by zero encountered in scalar divide
  return ndata / np.sum(np.log((data - location) / scale))
c:\Users\sussi\OneDrive\Documents\Denseflow\DenseFlow_Tool\.venv_py38\lib\site-packages\scipy\stats\_continuous_distns.py:6955: RuntimeWarning: invalid value encountered in scalar subtract
  return dL_dLocation(shape, location) - dL_dScale(shape, scale)

finished computing weight matrix
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
::::matricize time cost:  0.33027229999993324
matricize 29529x39517 and svd dense... ...
::::Finish Init @  0.41492679999998927
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
....
*** *** shaving opt size: 4
*** *** shaving opt value: 4.022239608827926
=== === improved opt size: 4
=== === improved opt value: 4.022239608827926
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 1.3669003723665814
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
..
*** *** shaving opt size: 2
*** *** shaving opt value: 2.708935584020059
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
...
*** *** shaving opt size: 3
*** *** shaving opt value: 0.9141095445163271
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 1.6243971945889435
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
..
*** *** shaving opt size: 2
*** *** shaving opt value: 0.0035806674674313216
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
......................................
*** *** shaving opt size: 38
*** *** shaving opt value: 0.2143533858380568
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.....................
*** *** shaving opt size: 21
*** *** shaving opt value: 0.09884530955140859
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................
*** *** shaving opt size: 34
*** *** shaving opt value: 0.1152696953714159
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 7
*** *** shaving opt value: 0.0011945706309687903
::::Finish Algorithm @  1.8488148999999794
removing 4 rows from graph
removing 4 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29529x39517 and svd dense... ...
::::Finish Init @  0.10566310000001522
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
..
*** *** shaving opt size: 2
*** *** shaving opt value: 2.708935584020059
=== === improved opt size: 2
=== === improved opt value: 2.708935584020059
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 1.6243971945889435
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
......................................
*** *** shaving opt size: 38
*** *** shaving opt value: 0.2143533858380568
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.....................
*** *** shaving opt size: 21
*** *** shaving opt value: 0.09884530955140859
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................
*** *** shaving opt size: 34
*** *** shaving opt value: 0.1152696953714159
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 7
*** *** shaving opt value: 0.0011945706309687903
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
........................
*** *** shaving opt size: 24
*** *** shaving opt value: 0.24359312836819708
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.........................
*** *** shaving opt size: 25
*** *** shaving opt value: 0.03160300114972221
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.00030263586982014163
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.........................
*** *** shaving opt size: 25
*** *** shaving opt value: 0.025839985484651815
::::Finish Algorithm @  1.713838600000031
removing 2 rows from graph
removing 2 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29529x39517 and svd dense... ...
::::Finish Init @  0.09854859999995824
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
......................................
*** *** shaving opt size: 38
*** *** shaving opt value: 0.2143533858380568
=== === improved opt size: 38
=== === improved opt value: 0.2143533858380568
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.....................
*** *** shaving opt size: 21
*** *** shaving opt value: 0.09884530955140859
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................
*** *** shaving opt size: 34
*** *** shaving opt value: 0.1152696953714159
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 7
*** *** shaving opt value: 0.0011945706309687903
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
........................
*** *** shaving opt size: 24
*** *** shaving opt value: 0.24359312836819708
=== === improved opt size: 24
=== === improved opt value: 0.24359312836819708
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.........................
*** *** shaving opt size: 25
*** *** shaving opt value: 0.03160300114972221
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.00030263586982014163
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.........................
*** *** shaving opt size: 25
*** *** shaving opt value: 0.025839985484651815
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
............
*** *** shaving opt size: 12
*** *** shaving opt value: 0.08782115753412927
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.....................................
*** *** shaving opt size: 36
*** *** shaving opt value: 0.019042535034774422
::::Finish Algorithm @  1.6317831999999726
removing 24 rows from graph
removing 24 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29529x39517 and svd dense... ...
::::Finish Init @  0.11731039999995119
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
......................................
*** *** shaving opt size: 38
*** *** shaving opt value: 0.2143533858380568
=== === improved opt size: 38
=== === improved opt value: 0.2143533858380568
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.....................
*** *** shaving opt size: 21
*** *** shaving opt value: 0.09884530955140859
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
..................................
*** *** shaving opt size: 34
*** *** shaving opt value: 0.1152696953714159
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 7
*** *** shaving opt value: 0.0011945706309687903
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.........................
*** *** shaving opt size: 25
*** *** shaving opt value: 0.03160300114972221
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.00030263586982014163
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.........................
*** *** shaving opt size: 25
*** *** shaving opt value: 0.025839985484651815
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.....................................
*** *** shaving opt size: 36
*** *** shaving opt value: 0.019042535034774422
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
..............................
*** *** shaving opt size: 30
*** *** shaving opt value: 0.010386748076143752
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.0019467122510239251
::::Finish Algorithm @  1.7698087999999643
removing 38 rows from graph
removing 38 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29529x39517 and svd dense... ...
::::Finish Init @  0.09806889999993018
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.....................
*** *** shaving opt size: 21
*** *** shaving opt value: 0.09884530955140859
=== === improved opt size: 21
=== === improved opt value: 0.09884530955140859
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.00030263586982014163
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
..................
*** *** shaving opt size: 18
*** *** shaving opt value: 0.01112787338232485
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.0019467122510239251
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.........................................
*** *** shaving opt size: 41
*** *** shaving opt value: 0.04989758783370213
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.........
*** *** shaving opt size: 4
*** *** shaving opt value: 0.001436606360482448
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 7
*** *** shaving opt value: 0.0014248341826453596
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
...........
*** *** shaving opt size: 11
*** *** shaving opt value: 0.0018221379302836352
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.........
*** *** shaving opt size: 8
*** *** shaving opt value: 0.016523968854082048
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.002680380772836786
::::Finish Algorithm @  1.5269680999999764
removing 21 rows from graph
removing 21 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29529x39517 and svd dense... ...
::::Finish Init @  0.15360179999993306
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.00030263586982014163
=== === improved opt size: 1
=== === improved opt value: 0.00030263586982014163
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.0019467122510239251
=== === improved opt size: 1
=== === improved opt value: 0.0019467122510239251
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.........................................
*** *** shaving opt size: 41
*** *** shaving opt value: 0.04989758783370213
=== === improved opt size: 41
=== === improved opt value: 0.04989758783370213
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 4
*** *** shaving opt value: 0.0014365745860973826
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
...........
*** *** shaving opt size: 11
*** *** shaving opt value: 0.0018221379302836352
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.........
*** *** shaving opt size: 8
*** *** shaving opt value: 0.016523968854082048
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.002680380772836786
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
.................
*** *** shaving opt size: 3
*** *** shaving opt value: 0.05565054318679176
=== === improved opt size: 3
=== === improved opt value: 0.05565054318679176
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
...........
*** *** shaving opt size: 10
*** *** shaving opt value: 0.054877745578120904
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 7
*** *** shaving opt value: 0.00039868425474085195
::::Finish Algorithm @  1.54862049999997
removing 3 rows from graph
removing 3 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29529x39517 and svd dense... ...
::::Finish Init @  0.1219363999999814
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.00030263586982014163
=== === improved opt size: 1
=== === improved opt value: 0.00030263586982014163
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.0019467122510239251
=== === improved opt size: 1
=== === improved opt value: 0.0019467122510239251
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 4
*** *** shaving opt value: 0.0014365745860973826
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
.......................................
*** *** shaving opt size: 39
*** *** shaving opt value: 0.04738318394619504
=== === improved opt size: 39
=== === improved opt value: 0.04738318394619504
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
...........
*** *** shaving opt size: 11
*** *** shaving opt value: 0.0018221379302836352
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.........
*** *** shaving opt size: 8
*** *** shaving opt value: 0.016523968854082048
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.002680380772836786
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
................
*** *** shaving opt size: 11
*** *** shaving opt value: 0.020416180555691894
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
...........
*** *** shaving opt size: 11
*** *** shaving opt value: 0.007300061236663409
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
..............
*** *** shaving opt size: 14
*** *** shaving opt value: 0.0019747009257595105
::::Finish Algorithm @  1.4343088000000535
removing 39 rows from graph
removing 39 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29529x39517 and svd dense... ...
::::Finish Init @  0.16482269999994514
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.00030263586982014163
=== === improved opt size: 1
=== === improved opt value: 0.00030263586982014163
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.0019467122510239251
=== === improved opt size: 1
=== === improved opt value: 0.0019467122510239251
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 4
*** *** shaving opt value: 0.0014365745860973826
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
...........
*** *** shaving opt size: 11
*** *** shaving opt value: 0.0018221379302836352
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.........
*** *** shaving opt size: 8
*** *** shaving opt value: 0.016523968854082048
=== === improved opt size: 8
=== === improved opt value: 0.016523968854082048
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.002680380772836786
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 7
*** *** shaving opt value: 0.00039868425474085195
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
..............
*** *** shaving opt size: 14
*** *** shaving opt value: 0.0019747009257595105
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.0008254836998038033
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
..................
*** *** shaving opt size: 18
*** *** shaving opt value: 0.041770087917301114
=== === improved opt size: 18
=== === improved opt value: 0.041770087917301114
::::Finish Algorithm @  1.5347889999999325
removing 18 rows from graph
removing 18 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29529x39517 and svd dense... ...
::::Finish Init @  0.13303990000008525
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.00030263586982014163
=== === improved opt size: 1
=== === improved opt value: 0.00030263586982014163
process 2-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.0019467122510239251
=== === improved opt size: 1
=== === improved opt value: 0.0019467122510239251
process 3-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 4
*** *** shaving opt value: 0.0014365745860973826
process 4-th singular vector
*** *** shaving ...
set up the greedy min tree
...........
*** *** shaving opt size: 11
*** *** shaving opt value: 0.0018221379302836352
process 5-th singular vector
*** *** shaving ...
set up the greedy min tree
.........
*** *** shaving opt size: 8
*** *** shaving opt value: 0.016523968854082048
=== === improved opt size: 8
=== === improved opt value: 0.016523968854082048
process 6-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.002680380772836786
process 7-th singular vector
*** *** shaving ...
set up the greedy min tree
.......
*** *** shaving opt size: 7
*** *** shaving opt value: 0.00012558225381358682
process 8-th singular vector
*** *** shaving ...
set up the greedy min tree
..............
*** *** shaving opt size: 14
*** *** shaving opt value: 0.0019747009257595105
process 9-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.0008254836998038033
process 10-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.26669696306142887
=== === improved opt size: 1
=== === improved opt value: 0.26669696306142887
::::Finish Algorithm @  1.4155064999999922
removing 1 rows from graph
removing 1 rows from tensor
alg: fastgreedy
	+ # of singlular vectors: 10

initial start
Generate tensorfile with time rescale:  1
matricize 29529x39517 and svd dense... ...
::::Finish Init @  0.12273469999990994
fast greedy algorithm ...
process 1-th singular vector
*** *** shaving ...
set up the greedy min tree
.
*** *** shaving opt size: 1
*** *** shaving opt value: 0.00030263586982014163
=== === improved opt size: 1
=== === improved opt value: 0.00030263586982014163
process 2-th singular vector

c:\Users\sussi\OneDrive\Documents\Denseflow\DenseFlow_Tool\.venv_py38\lib\site-packages\scipy\stats\_continuous_distns.py:6932: RuntimeWarning: divide by zero encountered in scalar divide
  return ndata / np.sum(np.log((data - location) / scale))
c:\Users\sussi\OneDrive\Documents\Denseflow\DenseFlow_Tool\.venv_py38\lib\site-packages\scipy\stats\_continuous_distns.py:6955: RuntimeWarning: invalid value encountered in scalar subtract
  return dL_dLocation(shape, location) - dL_dScale(shape, scale)

	Row and nonzero columns 8 x 6, edge size: 14 with camouflage.
block23:
	objective value 0.030761775894791763
	Node size: 11 x 1, edge size 5
	Row and nonzero columns 11 x 6, edge size: 16 with camouflage.
block24:
	objective value 0.05375774723376626
	Node size: 19 x 0, edge size 0
	Row and nonzero columns 19 x 92, edge size: 135 with camouflage.
block25:
	objective value 0.0014365745860973826
	Node size: 4 x 1, edge size 4
	Row and nonzero columns 4 x 3, edge size: 8 with camouflage.
block26:
	objective value 0.04629892062749751
	Node size: 3 x 1, edge size 1
	Row and nonzero columns 3 x 3, edge size: 5 with camouflage.
block27:
	objective value 0.05823601982349506
	Node size: 4 x 1, edge size 3
	Row and nonzero columns 4 x 2, edge size: 5 with camouflage.
block28:
	objective value 0.0008254836998038033
	Node size: 1 x 1, edge size 1
	Row and nonzero columns 1 x 1, edge size: 1 with camouflage.
block29:
	objective value 0.03315435612732929
	Node size: 5 x 1, edge size 3
	Row and nonzero columns 5 x 4, edge size: 8 with camouflage.
block30:
	objective value 0.020559074270943656
	Node size: 4 x 1, edge size 2
	Row and nonzero columns 4 x 3, edge size: 6 with camouflage.
Completed PlusTokenPonzi  k= 30  level=3 result calculation and storage

In [11]:
caseing = ['AlphaHomora', 'CryptopiaHacker', 'PlusTokenPonzi']
for casename in caseing:
    gpath = './Maxflow_graph/'+casename+'/'
    already = os.path.exists(gpath+'start_nodes.npy')
    if not already:
        print('Constructing graph')
        start_nodes,end_nodes,capacities,nodenum = build_g(casename)
    else:
        print('Reading')
        start_nodes,end_nodes,capacities,nodenum = read_g(casename)
    sourceadds = saddset[casename]
    if sourceadds[0] not in nodenum:
        print('Source address not in graph, skipping case:', casename)
        continue
    for k in [10, 30]:
        level = 3
        print('Calculating k=',k,' level=',level,'ing')
        r=output_flow_add(casename,k,level,sourceadds[0])
    print('Completed')

Constructing graph
构造图ing
完成构建图，节点数： 29696 边数： 83441
new folder
Calculating k= 10  level= 3 ing
当前正在运行： AlphaHomora k= 10 level= 3
读取对应heist地址...
已完成构建，读取图ing
读取完成
进行最大流算法...
共 0 条非0流，总流值： 0
地址存储中...
new folder
Calculating k= 30  level= 3 ing
当前正在运行： AlphaHomora k= 30 level= 3
读取对应heist地址...
已完成构建，读取图ing
读取完成
进行最大流算法...
共 0 条非0流，总流值： 0
地址存储中...
There is this folder
Completed
Constructing graph
构造图ing
完成构建图，节点数： 84862 边数： 315163
new folder
Calculating k= 10  level= 3 ing
当前正在运行： CryptopiaHacker k= 10 level= 3
读取对应heist地址...
已完成构建，读取图ing
读取完成
进行最大流算法...
共 0 条非0流，总流值： 0
地址存储中...
new folder
Calculating k= 30  level= 3 ing
当前正在运行： CryptopiaHacker k= 30 level= 3
读取对应heist地址...
已完成构建，读取图ing
读取完成
进行最大流算法...
共 0 条非0流，总流值： 0
地址存储中...
There is this folder
Completed
Reading
已完成构建，读取图ing
读取完成
Calculating k= 10  level= 3 ing
当前正在运行： PlusTokenPonzi k= 10 level= 3
读取对应heist地址...
已完成构建，读取图ing
读取完成
进行最大流算法...
共 174 条非0流，总流值： 2334662
地址存储中...
There is this folder
Calculating k= 30  level= 3 ing
当前正在运行： PlusTokenPonzi k= 30 level= 3
读取对应heist地址...
已完成构建，读取图ing
读取完成
进行最大流算法...
共 360 条非0流，总流值： 2383545
地址存储中...
There is this folder
Completed

In [12]:
g = os.walk(f'./Result/')  
cases = []
for path,dir_list,file_list in g:  
    for dir_name in dir_list:  
        cases.append(str(dir_name[0:-4]))
        print(dir_name[0:-4])
TUANHUOJIANCE(cases,k)

AlphaHomora
CryptopiaHacker
PlusTokenPonzi
缺少结果文件 AlphaHomora_k_30_level_0
缺少结果文件 AlphaHomora_k_30_level_1
缺少结果文件 AlphaHomora_k_30_level_2
缺少结果文件 AlphaHomora_k_30_level_3
缺少结果文件 CryptopiaHacker_k_30_level_0
缺少结果文件 CryptopiaHacker_k_30_level_1
缺少结果文件 CryptopiaHacker_k_30_level_2
缺少结果文件 CryptopiaHacker_k_30_level_3
缺少结果文件 PlusTokenPonzi_k_30_level_0
缺少结果文件 PlusTokenPonzi_k_30_level_1
缺少结果文件 PlusTokenPonzi_k_30_level_2
缺少结果文件 PlusTokenPonzi_k_30_level_3

,precision_level_0,precision_level_1,precision_level_2,precision_level_3,recall_level_0,recall_level_1,recall_level_2,recall_level_3
AlphaHomora,-1,-1,-1,-1,-1,-1,-1,-1
CryptopiaHacker,-1,-1,-1,-1,-1,-1,-1,-1
PlusTokenPonzi,-1,-1,-1,-1,-1,-1,-1,-1

In [13]:
import pandas as pd

casename = ['AlphaHomora', 'CryptopiaHacker', 'PlusTokenPonzi']
k_values = [10, 30]
level = 3

rows = []
for casename in cases:
    for k in k_values:
        metrics = check_metrics_my(casename, level=level, k=k)
        pre, mcr, msize = metrics['HOLO+MAXFLOW']
        rows.append({
            'case': casename,
            'k': k,
            'level': level,
            'precision': pre,
            'mcr': mcr,
            '|M|': msize,
        })

metrics_df = pd.DataFrame(rows)
display(metrics_df)

#out_csv = './Result/metrics_level_3_k_10_30.csv'
#out_xlsx = './Result/metrics_level_3_k_10_30.xlsx'
#metrics_df.to_csv(out_csv, index=False)
#with pd.ExcelWriter(out_xlsx) as writer:
#    metrics_df.to_excel(writer, index=False)

HOLO+MAXFLOW (level=3 k=10)
总共找出： 19 找出正确的：(heist) 0 ，
正确率(Precision): 0.0 ,
召回率（Recall）： 0.0


追踪金额： 1.247272562711582e-16 涉案金额： 3.961512135163169e-14 资金覆盖率: 0.0031484759358441513
账户总数： 29696 检测heist： 19

HOLO+MAXFLOW (level=3 k=30)
总共找出： 49 找出正确的：(heist) 6 ，
正确率(Precision): 0.12244897959183673 ,
召回率（Recall）： 0.0008620689655172414


追踪金额： 1.76184446534355e-16 涉案金额： 3.961512135163169e-14 资金覆盖率: 0.004447403933727902
账户总数： 29696 检测heist： 49

HOLO+MAXFLOW (level=3 k=10)
总共找出： 20 找出正确的：(heist) 2 ，
正确率(Precision): 0.1 ,
召回率（Recall）： 0.00022760896779333106


追踪金额： 1.5428956000978722e-13 涉案金额： 3.6410920922556475e-13 资金覆盖率: 0.4237452832845138
账户总数： 84862 检测heist： 20

HOLO+MAXFLOW (level=3 k=30)
总共找出： 74 找出正确的：(heist) 5 ，
正确率(Precision): 0.06756756756756757 ,
召回率（Recall）： 0.0005690224194833276


追踪金额： 5.806772232827564e-13 涉案金额： 3.6410920922556475e-13 资金覆盖率: 1
账户总数： 84862 检测heist： 74

HOLO+MAXFLOW (level=3 k=10)
总共找出： 19559 找出正确的：(heist) 19364 ，
正确率(Precision): 0.9900301651413671 ,
召回率（Recall）： 0.6290689363913976


追踪金额： 11109681.396828694 涉案金额： 13362800.697431086 资金覆盖率: 0.8313886922645236
账户总数： 34521 检测heist： 19559

HOLO+MAXFLOW (level=3 k=30)
总共找出： 19940 找出正确的：(heist) 19604 ，
正确率(Precision): 0.9831494483450351 ,
召回率（Recall）： 0.6368657007341954


追踪金额： 11160312.196686883 涉案金额： 13362800.697431086 资金覆盖率: 0.8351776285066036
账户总数： 34521 检测heist： 19940

              case   k  level  precision       mcr    |M|
0      AlphaHomora  10      3   0.000000  0.003148     19
1      AlphaHomora  30      3   0.122449  0.004447     49
2  CryptopiaHacker  10      3   0.100000  0.423745     20
3  CryptopiaHacker  30      3   0.067568  1.594789     74
4   PlusTokenPonzi  10      3   0.990030  0.831389  19559
5   PlusTokenPonzi  30      3   0.983149  0.835178  19940